name: Linter untuk Javascript

# Trigger
on: push

# Jobs
jobs:
  super-linter:
    # OS Action ini dijalan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v4.8.1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
